// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwsfycojxqlwhdppchud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3c2Z5Y29qeHFsd2hkcHBjaHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTAyMDMsImV4cCI6MjA2MjI2NjIwM30.zCUZu_ztHvYqKTPi_3g5yU85S7PJaOouSml1mJh9k14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);